### ISSUE TITLE
CSS grid

### ISSUE THREAD

**Issue by Perkin5** [y0ssar1an/CSS3#100]
'grid-gap' or 'grid-row-gap' etc are not being highlighted. Are you going to update the package to include the full css-grid spec?

**Comment by y0ssar1an** [comment]
Those properties have been [renamed](https://drafts.csswg.org/css-grid/#change-2016-grid-gap).
```
grid-gap -> gap
grid-column-gap -> column-gap
grid-row-gap -> row-gap
```
CSS3 labels the grid-gap properties as `invalid.deprecated.css`. Most color schemes will apply bright styling to that text to draw your attention. You may be using a color scheme that doesn't apply any styling, in which case it would look like CSS3 was missing the property.

**Comment by Perkin5** [comment]
Neither Chrome nor Firefox seem to support the renamed properties though the old ones still work.
