### ISSUE TITLE
Appears to cause recursion with ASP/HTML

### ISSUE THREAD

**Issue by peterh-capella** [y0ssar1an/CSS3#103]
With CSS3 installed and the default CSS syntax highlighting disabled, opening a classic ASP file brings up this error:

![screen shot 2018-05-14 at 8 33 27 am](https://user-images.githubusercontent.com/1122723/40000560-bdaa0154-5751-11e8-98fa-838df9738ece.png)

When CSS3 is disabled, the error does not occur.

**Comment by y0ssar1an** [comment]
Thanks for reporting. I believe I've fixed the bug in #108. Version 2.1.18 should be out on Package Control shortly. Please reopen if you still experience this bug.

Sorry it took so long to fix.
