### ISSUE TITLE
If install this package,there was an error for ruby slim package

### ISSUE THREAD

**Issue by qixingchong** [y0ssar1an/CSS3#104]
error info:"Error loading syntax file "Packages/Ruby Slim/Syntaxes/Ruby Slim.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit"

but if i uninstall this package,everything will be normal.
Has anyone experienced such an error?

sublime text 3 version 3.1.1 3176

**Comment by quocnam90dev** [comment]
"ignored_packages":
    [
        "Markdown",
        "Vintage"
    ],

**Comment by y0ssar1an** [comment]
I believe this is fixed in #108. Please reopen if you experience the problem again with version 2.1.18 or higher.
