### ISSUE TITLE
No SCSS support.

### ISSUE THREAD

**Issue by faisaljanjuah** [y0ssar1an/CSS3#106]
if we work in scss it shows some CSS errors. like :before and scss variables etc.
It is really nice package and if it adds scss support then it will be wonderful :)

**Comment by FL-KJ** [comment]
It would indeed be wonderful, but sadly it's not going to happen as stated [here](https://github.com/y0ssar1an/CSS3/issues/95#issuecomment-380989328):

> I'm sorry but SASS support is not possible. The syntax definition is 10k lines that are highly specific to CSS syntax. SCSS syntax diverges too much from CSS.
> 
> As an alternative, I can only suggest cssnext, which is fully supported. It has most of the SASS features you want, with a syntax that arguably is CSS (because it's based on W3C draft specs).

**Comment by alo0oz** [comment]
if full sass support is not possible, that's OK, but it would have been nice if the scope of the autocompletion included sass/scss documents. Now i have to change the syntax to css3 to gain the available css3 autocompletion.

**Comment by faisaljanjuah** [comment]
If extension is made using modular approach then I don't think it is hard to add more auto-completion properties. like SCSS have few more rules same as CSS, and think if CSS announce few more properties then it would be same hard to add them in this extension?
my point is just to add variable attribute ($foo) and include attribute for any mixin (@include mixinName( ); ) 
I tried to add SCSS syntax extension but activating that syntax takes all features of CSS3 syntax that is not acceptable :(

**Comment by y0ssar1an** [comment]
Sorry, but this syntax definition is highly specific to CSS. It wasn't written with SCSS in mind. It's not possible to modify it to support SCSS. It would have to be rewritten from scratch.
