### ISSUE TITLE
Error loading php syntax

### ISSUE THREAD

**Issue by G4Zz0L1** [y0ssar1an/CSS3#109]
`Error loading syntax file "Packages/PHP/PHP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

It seems that the error it's still there, even with the https://github.com/y0ssar1an/CSS3/pull/108

I've tried wiping cache files, and the plugin it's updated to version 2.1.18

**Comment by y0ssar1an** [comment]
Dup of #107
