### ISSUE TITLE
variable numbers/units have no coloring

### ISSUE THREAD

**Issue by runxel** [y0ssar1an/CSS3#112]
As you can see units and numbes of variables are white and not styled correctly.

![root var](https://user-images.githubusercontent.com/2277182/67639198-31ec0600-f8ed-11e9-89ac-01a8575743b0.png)

**Comment by y0ssar1an** [comment]
It looks like the custom property isn't getting matched correctly. It will take some time to investigate this. Thanks for reporting!

**Comment by LOQUILLO** [comment]
Hi @y0ssar1an maybe you need create a new scope for this variables con '--'
