### ISSUE TITLE
!important not autocomplete and and automate placing semicolon and colon

### ISSUE THREAD

**Issue by dare023** [y0ssar1an/CSS3#12]
Hi, thank you for this extension!
I have small issues:
- !important does not autocomplete
- how to make automatic placement of colon then space and semicolon?
If that is possible at all :)

**Comment by anyotherway** [comment]
CSS3 fails standard formatting, opting for compression that makes code unintelligible for other CSS add-ins, and for most human beings: 
fails standard spacing around 'curly brackets' for each selector value in the selector declaration. 
fails standard spacing around 'colon' for each selector value in the selector declaration. 
fails standard spacing around 'semicolon' for each selector value in the selector declaration. 
fails to add colon s[ace semicolon after inserting chosen selector (/) or knocks out this capability in ST3.
If you don't know how to space CSS, check out "CSS Format" by Mutian, focusing on all formatting except 'Compressed'.
http://mutian.github.io/Sublime-CSS-Format/
Thanks to expert advice most of CSS3 formatting can be corrected with Key Bindings -- user...
Example from novice hell...
a {| 
// results a {|} i.e., 'a {}' - look for solution in Key Bindongs -- default
// Auto-pair curly brackets
{ "keys": ["{"], "command": "insert_snippet", "args": {"contents": "{ $0 }"} },
// key bindings above now auto adjusts 'a {' to 'a {  }...
a { | } 
// good start, now try something to get CSS declaration property selection or colon keypress to suto insert standard property colon semicolon spacing, with semicolon advancing to space as managed by ST2 for years... 
{ "keys": [":"], "command": "insert", "args": {"characters": ": "} },
// this string sets the colon right but dumps the following semicolon
a { color: | } 
// still failed formatting, should be a { color: |; }, i.e., 'a { color: ; }'
So how to add semicolon, while keeping cursor position? 
And so on. If you get the above added, then still missing old ST2 semicolon key press advancing cursor one space in position for next property, or curly bracket key press moving cursor left of exising curly bracket without adding anything.
You know how it works in ST2.
More directly, when will CSS3 respect basic CSS3 formatting?
Same mess growing of late with CSS3_Syntax in ST2.
Please doctor 0ssar1an, we all need you to operate, ASAP.
refs: 
http://superuser.com/questions/540077/automatically-insert-a-space-between-parentheses-in-sublime-text-2
http://stackoverflow.com/questions/10931866/how-to-add-space-after-a-colon-in-css-with-sublime-text-2
"CSS3" is a very popular and useful tool. Sure wish you would please complete CSS formatting. 
No idea how it is done, but the expert contributed strings above should help.
You just need to add and the semicolon, and add the colon-space(cursor)-semicolon on snippet CSS3 property insertion. 
Should fascinate you for a few hours and bring relief to thousands. 
Thanks.

**Comment by variadico** [comment]
The point of CSS3 is simply syntax highlighting. CSS3 **does not** format code, minify code, or prevent anyone from formatting CSS the way they want.

If you want to format your CSS, then either do it by hand or use a CSS auto-formatter. This plugin, CSS3, is not an auto-formatter.

**Comment by anyotherway** [comment]
Thank you for sorting it out, Jaime! CSS3 Package corrupts CSS and HTML formatting by removing helpful space inserts and causing auto inserting of extra <<left tags, “parse” and dozens of unexpected others when default Sublime completions attempt to run. Also, huge numbers of new completion choices that CSS3 Package dumps into ST3 more annoying than helpful. Perhaps like left carrot-etc pollution, simple overload of something. Btw Sunburst theme seems to like your current release best for DOM coding (with/without almost same). Selector attributes and more to come. Sorry to rock your boat, CSS3 does format lots, not the good way. Keep up the good work best you can.

**Comment by y0ssar1an** [comment]
I don't understand what the issue is. Can you take a screenshot or GIF of the problem? Also, please use proper [markdown](https://help.github.com/articles/github-flavored-markdown/) formatting in your posts. It's almost unreadable.

**Comment by variadico** [comment]
Also, try disabling all other plugins. There's probably another plugin affecting the formatting.

**Comment by anyotherway** [comment]
In the middle of re-installing windows and sublime over and over, st2-st3-st2-st3-st2-st3.

Re markdown <https://help.github.com/articles/github-flavored-markdown/>  please, send your complaints to Microsoft and Git administrations, and boo Outlook. 

Win-build600-st2, win-buil601-st3, win-build602-st2…last complaint over 24 hours old

like, you must live in a stable house!

**Comment by y0ssar1an** [comment]
Are you making these posts through email? You can make the posts directly [here](https://github.com/y0ssar1an/CSS3/issues/12)
