### ISSUE TITLE
How about support svg element style?

### ISSUE THREAD

**Issue by oliverzy** [y0ssar1an/CSS3#14]
```
.node circle {
  cursor: pointer;
  fill: #fff;
  stroke: steelblue;
  stroke-width: 1.5px;
}

.node text {
  font-size: 11px;
}

path.link {
  fill: none;
  stroke: #ccc;
  stroke-width: 1.5px;
}
```

**Comment by littlefyr** [comment]
You should note that some of the items in you "BAD_CSS" gist listed as not being standards track are actually SVG standard properties. You can also look at the list here: http://www.w3.org/TR/SVG/styling.html. One thing to keep an eye on is that SVG occasionally (and I'm hard pressed at the moment to remember which) has different values for a property shared with CSS. I can't remember which but its worth double checking the overlaping properties

**Comment by y0ssar1an** [comment]
Sorry for the lack of communication about SVG support. I have a job now, so finding time to work on the plugin is a lot harder. I've decided to put off adding SVG support until the [SVG 2 spec](https://svgwg.org/svg2-draft/) is further along. SVG 2 will hopefully be more in sync with CSS3, meaning properties that are deprecated in CSS3 are also deprecated in SVG. The CR of SVG 2 is [due in May](http://www.w3.org/Graphics/SVG/WG/wiki/SVG2_Planning_Page#Milestones).

**Comment by y0ssar1an** [comment]
Just pushed v1.3.0 with full SVG2 support. Thanks for your patience on this one :)
