### ISSUE TITLE
:before and :after selectors being flagged as deprecated

### ISSUE THREAD

**Issue by leem32** [y0ssar1an/CSS3#16]
Hi,
For some reason the pseudo selectors :before and :after are being flagged as deprecated.
If this is a bug which I'm assuming it is as it validates on W3C for CSS3, is their an quick way for me to fix it myself??

![style_tile_texture_013](https://cloud.githubusercontent.com/assets/10338315/5595738/fd86e4b0-9272-11e4-9838-8c822a8566c1.png)

Thanks :)

**Comment by pi241a** [comment]
**Note:** I'm not the maintainer.

The syntax highlighter is working correctly. In CSS3 pseudo-elements have two colons, while pseudo-classes only have one colon.

`:hover` is a pseudo-class
`::before` is a pseudo-element

The Spec: http://www.w3.org/TR/2009/PR-css3-selectors-20091215/#gen-content
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/::before

**Comment by eternal-sorrow** [comment]
This note about spec is right, but single-colon notation of pseudo-elements is still supported across all browsers and commonly used because double-colon notation is not supported by IE 8. Is there way to fix this on my local computer, if it doesn't go to upstream? These red highlights across all my stylesheet are very annoying and even distracting, because they look like real syntax errors.

**Comment by y0ssar1an** [comment]
Yeah, I took kind of a hard line on this when I was developing it. It's meant to be annoying, but if you're working with a bunch of legacy code or you have to support IE8, it's probably really annoying. Still, I'm tempted to just leave it alone. Browsers older than IE9 are getting pretty scarce. [This site](http://www.sitepoint.com/browser-trends-april-2015-statcounter-vs-netmarketshare/) has IE6/7/8 down to 3.33% of worldwide browsers.

If you want to fork CSS3, here's how you can disable it.

1) uninstall CSS3
2) clone this repo into `$YOUR_SUBLIME_TEXT_DIR/Packages/User`. 
3) switch to dev branch
4) comment out line: https://github.com/y0ssar1an/CSS3/blob/dev/CSS3.YAML-tmLanguage#L532
5) install AAAPackageDev through Package Control
6) use AAAPackageDev to compile your CSS3.YAML-tmLanguage file to a CSS3.tmLanguage file
7) switch back to master
8) `git checkout dev CSS3.tmLanguage`

**Comment by eternal-sorrow** [comment]
Thanks.
