### ISSUE TITLE
why can not support "-moz-transform" ?

### ISSUE THREAD

**Issue by mavict** [y0ssar1an/CSS3#19]
"-moz-transform"  can not be highlighted ! how to solve it ? thanks!

**Comment by y0ssar1an** [comment]
The `-moz-` prefix has been unnecessary since Firefox 16, according to [caniuse.com](http://caniuse.com/#feat=transforms2d). Unless you need to support very old versions of Firefox, it's safe to use the unprefixed version of `transform`.
