### ISSUE TITLE
Autocomplete automatically to press tab key within style tag

### ISSUE THREAD

**Issue by felipetiza** [y0ssar1an/CSS3#21]
In a html file, within of tag <style>, when you press tab key automatically write a word that sublime remember. It's impossible indent a line of code.

**Comment by y0ssar1an** [comment]
Perdón, no te pude entender. ¿Puedes decirlo en español?

**Comment by pi241a** [comment]
Actualmente, la característica de autocompletado, tanto como el coloreo de sintaxis, funciona dentro de un archivo HTML. Por lo menos en Sublime 3 (3080).

Pero quizá estas preguntado otra cosa...

**Comment by felipetiza** [comment]
Perdonad, no sabía que habláraiss español y lo siento por mi mala explicación antes.

Resulta que cuando trabajas con un fichero HTML, dentro de la etiqueta <style></style> pulso la tecla de tabulación y automáticamente me escribe una palabra o una linea de código (dependiendo lo que sublime recuerde que se haya escrito con anterioridad). Si vuelvo a dar a tabular me tabula la línea pero la palabra que antes escribió sola no está.

Así sucesivamente, tabula y escribe línea, vuelves a tabular y a borrar la línea. Sólo ocurre cuando tabulas dentro de la etiqueta <style> en un fichero .html

**Comment by pi241a** [comment]
¿Me puedes decir si este es tu problema?

![Problema21](http://zippy.gfycat.com/CreativeRawKentrosaurus.gif)

Si no lo es, entonces ¿crees que puedas subir un video o GIF del problema? Intenté reproducirlo, pero quizá sea más fácil verlo.

¡Gracias! :smile:

**Comment by felipetiza** [comment]
Acabo de descubrir que el error sólo me aparece cuando tengo activo el plugin CSS3 y SublimeCodeIntel, el cual éste si tienes activado el autocompletado aparece al tabular.

Por lo que veo puede que quizás sea un conflicto entre ambos pero no se bien porqué, ¿quizás la configuración que tengo? voy a seguir probando y buscando a ver si doy con el motivo. Pensaba en subir un vídeo para que se viera pero no se si ya sería necesario. Voy a ver porqué es y si no consigo dar con la clave lo subo para que lo veas.

**Comment by pi241a** [comment]
Ah, tal vez sea un conflicto entre ambas extensiones. Se reconoce que hay un problema entre CSS3 y Emmet. Quizá sea el caso entre CSS3 y SublimeCodeIntel.
