### ISSUE TITLE
Highlight and autocomplete for object-fit CSS3 property

### ISSUE THREAD

**Issue by tomsarduy** [y0ssar1an/CSS3#23]
Please, add suport for object-fit property, is not so common now but I think is time :)
![screen shot 2015-03-30 at 3 15 29 pm](https://cloud.githubusercontent.com/assets/1388092/6904560/a51e853c-d6ef-11e4-81ee-3e6b0b84d136.png)

**Comment by pi241a** [comment]
I've never used the ``object-fit`` property before, but did you forget a curly brace? This worked for me.

![object-fit](https://cloud.githubusercontent.com/assets/4296393/6910484/75ce862e-d708-11e4-803d-bef4626c7cd9.png)

More on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by y0ssar1an** [comment]
This looks to me like the same issue with the font property: a missing semicolon in property above `.entry-content`.
