### ISSUE TITLE
Add support for shorthand font property

### ISSUE THREAD

**Issue by tomsarduy** [y0ssar1an/CSS3#24]
Would be nice if you could add support for shorthand `font` property with a proper dispatcher:

> As with any shorthand CSS properties, the values which are not set in it are set to their individual initial values, eventually overriding values previously set using non-shorthand properties.

![screen shot 2015-03-30 at 3 28 00 pm](https://cloud.githubusercontent.com/assets/1388092/6904842/b2e3c89c-d6f1-11e4-8025-af592a546f33.png)

**Comment by pi241a** [comment]
This works for me.

````
body {
	font: italic small-caps normal 13px/150% Arial, Helvetica, sans-serif;
}
````

![font-prop](https://cloud.githubusercontent.com/assets/4296393/6910643/a9d77168-d70a-11e4-89c9-609931f09bcb.png)

**Comment by y0ssar1an** [comment]
@tomsarduy I'm unable to reproduce the issue on my machine. Is it possible that the last property defined above `.entry-content` is missing the trailing semicolon? This highlighter requires that all properties end with a semicolon, or the highlighting will break. This is for technical reasons as well as being a [best practice](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=Declaration_Stops#Declaration_Stops).

**Comment by tomsarduy** [comment]
@pi241a and @y0ssar1an, I'm sorry, the thing is that after an update the SCSS default highlight seems to be activated. I checked and is working perfectly, thanks for the good job :)
