### ISSUE TITLE
Missing clip property from CSS 2.1

### ISSUE THREAD

**Issue by pepelsbey** [y0ssar1an/CSS3#30]
![image](https://cloud.githubusercontent.com/assets/105274/7788623/401b0960-0243-11e5-8244-179aa2b96c58.png)

I’m not sure why CSS `clip` property is marked as “unsupported” or “obsolete” in #2, but [it’s a part of CSS 2.1 specification](http://www.w3.org/TR/CSS21/visufx.html#clipping) with is REC and widely implemented.

**Comment by y0ssar1an** [comment]
It's been [officially deprecated](http://www.w3.org/TR/css-masking/#clip-property). You're free to keep using it, of course. CSS3 is doing its job by notifying you that there's an issue.

**Comment by pepelsbey** [comment]
Kicking in the eye with a red brick is not “notifying” as for me. And what’s the point in such notification for me as a developer anyway? It will be supported forever for backward compatibility **and** there are no available alternatives yet. No, really, what’s the point? I’m not trying to be rude here, I’m trying to understand.

**Comment by variadico** [comment]
The point of using CSS3 is to help you follow standards. Those are the main selling points the author has in the [README.md](https://github.com/y0ssar1an/CSS3/blob/master/README.md). This plugin wasn't made to support legacy CSS on purpose.

**Comment by y0ssar1an** [comment]
I hear you @pepelsbey. It sucks when things get dropped from the spec and there's no standards-based, cross-browser alternative. There are many more examples besides `clip`. For example, the "star hack" (e.g. `*zoom: 1;`) was never intended to be in CSS. It was a bug that web developers started using. Then browsers _had_ to support it, even though nobody ever planned it or wanted it.

The Chromium CSS parser is currently being rewritten. That means some unlucky dev out there is currently trying to shiv support for the star hack into an already ridiculously complicated piece of software.

The "red brick" doesn't break your code. It just nags you. In your case, you saw the red brick and were like _What the hell?!_ Then you looked it up, and found out `clip` is non-standard.

![the_more_you_know](https://cloud.githubusercontent.com/assets/1250684/7790742/5817a4bc-0246-11e5-8f86-3c4278be8f34.gif)

Then you were like _Ok, so what the crap am I supposed to use?_, and the Internet Explorer team was like...

![okay_guy_ie](https://cloud.githubusercontent.com/assets/1250684/7790861/cac72968-0248-11e5-9811-a5aa421cb215.png)

I'm sorry @pepelsbey. Today the system failed you.
