### ISSUE TITLE
Duplicate css autocomplete

### ISSUE THREAD

**Issue by andremacola** [y0ssar1an/CSS3#34]
Duplicate CSS2 on autocomplete.. the first one always return without :;

![captura de tela 2015-06-17 as 22 10 30](https://cloud.githubusercontent.com/assets/3408809/8222177/0508d2d6-153e-11e5-9771-f3c402370fef.png)
![captura de tela 2015-06-17 as 22 12 53](https://cloud.githubusercontent.com/assets/3408809/8222178/050abd12-153e-11e5-9be0-51d6aad6fc88.png)

**Comment by variadico** [comment]
The maintainer says that you should disable the default CSS package.

https://github.com/y0ssar1an/CSS3#installation

**Comment by y0ssar1an** [comment]
@andremacola Can you confirm that disabling the default CSS package fixes the problem?
