### ISSUE TITLE
Disabling default CSS package prevents Goto symbol in project from working

### ISSUE THREAD

**Issue by benfrain** [y0ssar1an/CSS3#35]
As per the recommendations I disabled the default CSS package. However, when this is done, 'Goto symbol in project' stops working (one of the finest features of Sublime Text 3).

Is this a known side-effect? Is there a workaround or is it a case of having CSS3 and CSS to get that working but accepting the duplicate auto-complete recommendations?

**Comment by y0ssar1an** [comment]
Sorry. I don't have a workaround for you. I'm rewriting the syntax highlighter from scratch and this is one of the issues I hope to fix. I don't have a good understanding of how symbol indexing works yet.

Leaving the CSS package enabled isn't the end of the world, but as you point out, you'll get duplicate completions. Again, sorry for the bugs.

**Comment by benfrain** [comment]
@y0ssar1an sure, no problem. I'm about to start off on the syntax highlighting thing soon. You may find this thread useful: http://www.sublimetext.com/forum/viewtopic.php?f=6&t=18754&p=69343#p69343

**Comment by benfrain** [comment]
I should have updated this. This was a red herring. I actually had CSS files disabled from the binary_file_patterns object in Sublime (as I had been using Sass previously and didn't want to find symbols in CSS at that point).
