### ISSUE TITLE
Css Hex colors.

### ISSUE THREAD

**Issue by ctf0** [y0ssar1an/CSS3#36]
i dont know why some hex codes are yellow.
![screen shot 2015-07-08 at 10 56 39 pm](https://cloud.githubusercontent.com/assets/7388088/8581949/9b4c9f72-25cc-11e5-8357-1b52a3a98043.png)

**Comment by y0ssar1an** [comment]
Hmm. That's strange. Can you place the cursor in the yellow area, press `Ctrl+backtick`, type `print(view.scope_name(view.sel()[0].b))` and tell me what gets printed? Those are the scope names that are being assigned to the text. CSS3 assigns scope names to different regions of text, and your theme assigns colors to the scope names. Here's an example of the scope names from a random region of Python text.

    source.python meta.function.decorator.python entity.name.function.decorator.python 

Also, can you tell me what theme you're using? Thanks.

**Comment by variadico** [comment]
Does it matter that the hex values aren't in a valid declaration block?

Valid CSS
```css
body {
    color: #00a8c6;
}
```

Invalid CSS
```css
#00a8c6
```

**Comment by ctf0** [comment]
@y0ssar1an here is what i get from console `source.css meta.selector.css entity.other.attribute-name.id.css` and am using Seti_UX

**Comment by y0ssar1an** [comment]
Ok, the yellow text is being matched as an id selector, which makes sense. The text is at the top-level and starts with a `#` symbol. Does the problem persist if the hex colors are inside curly braces, as @variadico pointed out?

**Comment by ctf0** [comment]
nop
