### ISSUE TITLE
Completion for !important

### ISSUE THREAD

**Issue by MichaelTunnell** [y0ssar1an/CSS3#38]
I know this was already suggested and the issue was closed but it seemed to have been closed due to an unrelated reason.

I'd like to request that !important be added to the completion list because while I am aware that !important is bad practice as a reliance it is sometimes needed and to limit people who write good CSS because there are people who don't is removing practicality of this package.

I switched to this package from the default CSS syntax because it provides more completions such as box-sizing. transition, etc that the default syntax doesn't have. However, not having !important seems like regression to me.

I only use !important when I absolutely have to, such as some jackass throwing !important on their CSS in the plugin/platform code forcing me to do so.

Please, add it to the package so people who are responsible coders are not punished because of the irresponsible coders.

**Comment by y0ssar1an** [comment]
Yeah, I understand that in real-world code we have to make compromises (especially if you're working on a team). Is it really that bad to have to type `!important` without completions? It should still be getting highlighted just fine. I like that there's some friction when you want to try to use it. What do you think?

**Comment by MichaelTunnell** [comment]
sorry I never responded but I relunctantly agree. It isn't that big of a deal and maybe it is an improvement to remind people not to use it so fair enough.

**Comment by variadico** [comment]
Yeah, bad practices shouldn't be easy.

**Comment by jimbo1qaz** [comment]
I'm writing a resume generator in Pandoc, and would like to override my own Stylus user-styles (which replace body with "sans-serif" improving the appearance of most other websites). Having to type "!important" manually is jarring.
