### ISSUE TITLE
Not colourised

### ISSUE THREAD

**Issue by kud** [y0ssar1an/CSS3#43]
```style
    @media (min-width: 1600px) {
      html.naked-theme .pmd-HomepageHead--ads {
        padding-right: 420px;
      }
    }
```

![macosx 2015-11-25 at 18 06 38](https://cloud.githubusercontent.com/assets/655838/11403921/a512ebe2-939f-11e5-856c-85ce791e6719.png)

**Comment by y0ssar1an** [comment]
Yeah, this is [Issue #1], aka the most annoying bug that I've been unable to squash. The reason for this bug can be summarized as "trying to parse with regular expressions." The fix will only come when I rewrite the syntax definition from scratch in the new `sublime-syntax` format. I likely won't have time to start that for another few months. Until then, I'm sorry for the annoyance. The README shows a couple of ways to mitigate the issue.

**Comment by kud** [comment]
Okay thank you. :)
