### ISSUE TITLE
How to showing all CSS properties or value?

### ISSUE THREAD

**Issue by yisibl** [y0ssar1an/CSS3#49]
Simile Atom

![](https://img.alicdn.com/tps/TB1882kLXXXXXcBXFXXXXXXXXXX-406-332.png)
![](https://img.alicdn.com/tps/TB1w2ThLXXXXXX3XVXXXXXXXXXX-846-512.png)

http://stackoverflow.com/questions/24894201/package-for-showing-all-possible-css-values-in-sublime-text-2

**Comment by y0ssar1an** [comment]
`CSS3` should be offering you completions for properties and values. Press `ctrl+`` to check to console to make sure a file called `css3_completions.py` is getting loaded properly.
