### ISSUE TITLE
No Need For Disabling Emmet

### ISSUE THREAD

**Issue by mohamadnorouzi20** [y0ssar1an/CSS3#50]
There is no need for completely disabling Emmet.
You can simply disable css part by adding these to Emmet settings:

	"show_css_completions": false,
	"disable_tab_abbreviations_for_scopes": "source.css"

**Comment by y0ssar1an** [comment]
Thank you very much for this! I updated the install notes. They will no longer encourage people to disable Emmet.

**Comment by bradym80** [comment]
y0ssar1an, I followed the directions in the comments and added the following lines to Emmet.sublime-settings

  	"show_css_completions": false,
  	"disable_tab_abbreviations_for_scopes": "source.css"

When I save I receive the following error: Error trying to parse settings: Unexpected trailing characters in Packages/User/Emmet.sublime-settings:1:26

**Comment by mohamadnorouzi20** [comment]
@bradym80 You probably left a comma at last line.

**Comment by y0ssar1an** [comment]
This is my fault. The update message for version 1.2.16 (just released) has a comma at the end. 
```
    "show_css_completions": false,
    "disable_tab_abbreviations_for_scopes": "source.css",  <-- delete this if this is the last setting
```
