### ISSUE TITLE
Doesn't highlight next prop correctly if the previous prop doesn't end with a semicolon.

### ISSUE THREAD

**Issue by wzup** [y0ssar1an/CSS3#51]
Yes, I've read the BP section (https://github.com/y0ssar1an/CSS3#best-practices) that states "*End every property declaration with a semicolon.*"

However there is a `minifier` CLI utility (https://www.npmjs.com/package/minifier) that formats the code removing semicolons from the last prop and CSS3 doesn't highlight correctly any more:

![css min - sublime text 2016-01-25 13 29 23](https://cloud.githubusercontent.com/assets/3880497/12543219/301abae2-c368-11e5-9e76-d77770065b4d.png)

Is there a way to change this behavior? Some `true`/`false` option in config?

**Comment by variadico** [comment]
Every property must end with a semi-colon. It's in the readme.
https://github.com/y0ssar1an/CSS3#best-practices

**Comment by wzup** [comment]
Be sure, I read that.
I'm asking is there an option to control it?

**Comment by y0ssar1an** [comment]
There's no option, sorry. The syntax highlighter depends on those semicolons being there to differentiate between selectors and properties. I understand this breaks highlighting for minified CSS, but it would require a major overhaul. I'll try to get minified CSS working with the `sublime-syntax` rewrite, but no promises. Parsing with regular expressions sucks.
