### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by alexandredomain** [y0ssar1an/CSS3#52]
It seems to me that svg is not supported. Could you resolve it ? Thanks :)
![pb svg](https://cloud.githubusercontent.com/assets/16240391/12703556/53c0d408-c846-11e5-9b21-1a5132126245.png)

**Comment by y0ssar1an** [comment]
This is a dup of #14. The SVG 2 spec reached Candidate Recommendation status in August, so I'll be supporting it eventually. Thanks for your patience.

**Comment by alexandredomain** [comment]
Thanks. I can't wait! :)
