### ISSUE TITLE
Comments Initiated With `Ctrl+/` Lack the Standard Whitespace

### ISSUE THREAD

**Issue by lunacodes** [y0ssar1an/CSS3#53]
When you press `Ctrl+/`, the comments come out like '/*Comment Here*/' instead of `/* Comment Here */`

A simple edit to Comments.tmPreferences fixes this:

17: Change `<string>/*</string>` to `<string>/* </string>`
23: Change `<string>*/</string>` to `<string> */</string>`

Side Note: Sublime Text 3's default CSS Package has this same issue

**Comment by y0ssar1an** [comment]
Thanks for this! It'll be in the next release.
