### ISSUE TITLE
Can we have support for CSS variables?

### ISSUE THREAD

**Issue by srcspider** [y0ssar1an/CSS3#55]
Processors like PostCSS support them.

**Example**
```
:root {
	--image-path: 'path/to/module/images';
	--align: 'padding-top';
	--width: 100px;
}

.module {
	width: var(--width);
}

.module--special {
	--image-path: 'another/path/to/images';

	& > .module-Nav {
		background-image: url(var(--image-path, 'images')/nav-image.png);
		var(--align, padding-bottom): 10px;
	}
}
```

More examples in the official draft: https://drafts.csswg.org/css-variables/

**Comment by y0ssar1an** [comment]
The only short-term fix I can make is to highlight `var(--foo)` calls where `var()` is a function argument, e.g. `url(var(--myurl))`. The arguments to `var()` would still not be matched. That's not much of an improvement.

Proper variable support will have to wait until I rewrite the syntax highlighter in `sublime-syntax` format. I'm going to begin work on that soon. Variables and custom properties are at the top of my "must support" list for version 2.0.

**Comment by srcspider** [comment]
Thanks y0. Any little bit of extra syntax highlight would help even if only temporary since it prevents highlighting errors by forcing context rules. Sorry I should have probably posted a picture of how the code from the opening shows up:

![err](https://cloud.githubusercontent.com/assets/338910/14597788/9c128cbc-0557-11e6-84a5-4d7875f22a7b.png)

**Comment by kevinSuttle** [comment]
Here's how the CSS (not CSS3 package) renders them.

<img width="699" alt="screen shot 2016-06-07 at 12 14 49 pm" src="https://cloud.githubusercontent.com/assets/95672/15865635/89c6506a-2ca9-11e6-9716-489b4d7b5003.png">

**Comment by y0ssar1an** [comment]
Version 2.0.0 is out, with support for variables :)

**Comment by kevinSuttle** [comment]
Woot. Thanks!
