### ISSUE TITLE
Custom Element Support

### ISSUE THREAD

**Issue by jsilvermist** [y0ssar1an/CSS3#56]
Custom elements are currently not being highlighted at all.

If anything with a `-`(hyphen) such as `x-app` or `paper-material` was highlighted as a base element it would be much more consistent with default elements, without removing error correction by highlighting misspelled base elements, as an element without a hyphen couldn't be a custom element.

**Comment by y0ssar1an** [comment]
Yeah, I'm sorry. Custom elements are completely broken. Supporting them will require a rewrite of the syntax definition.

My top priorities for the `sublime-syntax` rewrite are:
- Fixing [Known Issues 1](#5)
- Variables
- Custom Elements

**Comment by y0ssar1an** [comment]
Version 2.0 is out, with custom element support :)
