### ISSUE TITLE
Attribute Selectors

### ISSUE THREAD

**Issue by bratukham** [y0ssar1an/CSS3#57]
When there is nothing before attribute selector it is not highlighted:
![image](https://cloud.githubusercontent.com/assets/1413357/15497325/7cc1fd84-219a-11e6-8a04-f18059efe391.png)

But this works as expected:
![image](https://cloud.githubusercontent.com/assets/1413357/15497368/bed41cf2-219a-11e6-984a-bbc72577b8a4.png)

**Comment by y0ssar1an** [comment]
Thank you very much for reporting this issue! I'm rewriting the highlighter from scratch as we speak. I hope to have it finished in a month or two. Now that I'm aware of the problem, I can make sure the new highlighter fixes this.

**Comment by y0ssar1an** [comment]
This problem has been fixed in the 2.0 syntax highlighter. No ETA on the release, but things are progressing smoothly. I still have a long ways to go, but I can't wait to show off the improvements! Thanks for your patience.

**Comment by y0ssar1an** [comment]
Fixed in 2.0
