### ISSUE TITLE
translateZ() Property Bug

### ISSUE THREAD

**Issue by danielnitu** [y0ssar1an/CSS3#58]
Hi, I found a bug for the *translateZ()* property of the transform function. After writing *transform: translate*, the drop-down list appears with all the options available. If you click on *translateZ()*, it will output *translateX()* instead. This happens every time.
Other than that, I find this support really helpful. Cheers!

**Comment by y0ssar1an** [comment]
Thank you very much for reporting this! I've fixed it in the 2.0 version, which should be out in the next few weeks.

https://github.com/y0ssar1an/CSS3/commit/188f7147a3ac5c3a492fb11d19327dcb35bbc176

**Comment by y0ssar1an** [comment]
Fixed in 2.0
