### ISSUE TITLE
I get an error for unbalanced curly braces that balanced

### ISSUE THREAD

**Issue by benfrain** [y0ssar1an/CSS3#62]
First, thanks for releasing v2 of this plugin!

I now have a small issue I didn't have before. As I write a nested syntax, this now produces an 'error' brace highlight on the final brace (I get the same for any block containing nested content):

````
html {
    &[data-showing-modal] {
        overflow: hidden;
    }
}
````

Is there a toggle I can use to switch off this balance checking?

**Comment by y0ssar1an** [comment]
This is a syntax I haven't seen before. I googled it and found [this spec](https://tabatkins.github.io/specs/css-nesting/). It's not on [w3.org](https://www.w3.org/Style/CSS/current-work.en.html), but it's from Tab Atkins, one of the primary contributors to the W3C specs. It looks like a preliminary spec to me. I'm definitely open to supporting it, though.

Are there browsers which support nested CSS? Is that code being preprocessed into non-nested CSS?

**Comment by benfrain** [comment]
Hi, no, it's essentially Sass syntax (although I don't use Sass, I'm using PostCSS). Not sure it should be supported as there are likely 5 or more different ways people do nesting with style sheets (LESS, Sass, W3C preliminary, etc). However, having the ability to switch off the balance checking would be useful.

If the W3C nesting spec ever becomes a thing, that would be the time to support nesting fully here IMHO, otherwise you will end up trying to cater to many different and non-standard implementations.

**Comment by alberto2000** [comment]
See #63

**Comment by y0ssar1an** [comment]
I'm closing this issue because there's no way to toggle this that I know of. I'll keep my fingers crossed that somebody forks this and makes dedicated packages for SCSS, PostCSS, etc.

**Comment by benfrain** [comment]
That's a shame as this package was working fine for me prior to v2. Never had any problems before.

**Comment by y0ssar1an** [comment]
Sorry about that! If you want to go back to v1, you can clone this repo directly into your Packages directory.
```sh
cd path/to/Packages
git clone git@github.com:y0ssar1an/CSS3.git
git checkout v1.3.3
```
I would then delete the `.git` directory, as having a git repo in your Packages directory can cause Package Control to break.

**Comment by benfrain** [comment]
Thanks Ryan, appreciate that. Will give it a whirl.
