### ISSUE TITLE
Integration with SCSS

### ISSUE THREAD

**Issue by alberto2000** [y0ssar1an/CSS3#63]
Is there any chance to integrate this within an SCSS syntax plugin?

**Comment by y0ssar1an** [comment]
This package targets CSS only, but it could potentially be forked and turned into an SCSS package. I'm not familiar with SCSS, so I can't say how much work it would be. I see that SCSS adds nested code blocks. Nesting is one of the trickiest things to get right, as I discovered implementing `@media` and `@supports`. If someone wants to take on that project, I'll help in any way I can.

**Comment by gkatsanos** [comment]
thats a blocking problem for me :(
