### ISSUE TITLE
Cosmetic issue with rules beginning with "@" (font-face, media, etc.)

### ISSUE THREAD

**Issue by FL-KJ** [y0ssar1an/CSS3#64]
Apologies if this is the wrong place, but I'm experiencing this new issue ever since the recent upgrade.

Whenever I add a comment before a rule beginning with "@", the selectors immediately afterwards are no longer highlighted correctly as shown in the screenshot below (normally I like to write "Media queries begin here" or something similar).

![html](https://cloud.githubusercontent.com/assets/20839685/17402754/a0706776-5a4c-11e6-9ef3-551c5f3a0431.PNG)

I encounter this issue when the syntax is set to HTML. Changing the syntax to CSS3 does fix the problem (see screenshot below) but obviously when you're working on a page which has HTML/JavaScript etc. the CSS3 syntax messes up the rest of the highlighting.

![css3](https://cloud.githubusercontent.com/assets/20839685/17402755/a0793040-5a4c-11e6-920d-b2368fc35d8a.PNG)

As I said, it only affects the first selectors - if I added more rules to the media query then they would be highlighted correctly.

Let me know if I've been unclear and I'll provide more information.

Thanks.

**Comment by FL-KJ** [comment]
No worries - thanks for the reply.

**Comment by y0ssar1an** [comment]
The problem is caused by the highlighter mismatching the comment as a `rule`. I can't thank you enough for reporting this. This was a pretty big bug. I also found another subtle bug with the `rule` context while I was debugging this problem. So good job, @FL-KJ!

The fix should be out shortly.

**Comment by FL-KJ** [comment]
No problem. If I encounter any more bugs I'll let you know.

I'm sure it goes without saying, but thanks for all your hard work on this plugin. As a front-end dev I use this every day and I can't imagine how tedious my job would become without it - your efforts are greatly appreciated.
