### ISSUE TITLE
Scrolls on Save

### ISSUE THREAD

**Issue by bautistaralphangelo** [y0ssar1an/CSS3#67]
`"format_on_save": true`

File scrolls upward when saving.

Using Sublime Text Build 3114

**Comment by y0ssar1an** [comment]
The config file has been completely stripped out of CSS3 2.0. All the settings were for the validator, which has been removed. If you upgraded from 1.0 like most people, the config file will still be there, but it shouldn't do anything. Also, I don't remember a `"format_on_save"` option being in CSS3. Was this intended for [`SublimeClangFormat`](https://github.com/rosshemsley/SublimeClangFormat/issues)?
