### ISSUE TITLE
Coloring of empty-cells?

### ISSUE THREAD

**Issue by EmilStenstrom** [y0ssar1an/CSS3#68]
<img width="224" alt="empty-cells incorrectly color coded" src="https://cloud.githubusercontent.com/assets/224130/18704609/e4ec6062-7fea-11e6-98bb-a7df054dfdd7.png">

This package nicely started color-coding the box-sizing property. But instead it seems empty-cells stopped working. Is this something you are aware of?

Reference: https://developer.mozilla.org/en/docs/Web/CSS/empty-cells

**Comment by y0ssar1an** [comment]
Thank you for reporting this! I did some quick research and it looks like this was an oversight on my part. `empty-cells` is in the CSS 2.1 spec. It's not in any CSS3 specs, but I can't find any mention of it being deprecated, so it probably should've been carried over.

I'll do some more thorough research and keep you updated. If it looks good, it should be very easy to add to the next release.

Thanks again!

**Comment by EmilStenstrom** [comment]
Thanks! Works great!

**Comment by y0ssar1an** [comment]
Thanks for testing! I'll push the update out to everybody this weekend. I just need to make a few more changes for yesterday's update to the CSS Values and Units spec.
