### ISSUE TITLE
CSS3 - Error Loading Syntax file

### ISSUE THREAD

**Issue by damonx23** [y0ssar1an/CSS3#71]
After updating the package/reinstalling I get the error message 
![css3 error message](https://cloud.githubusercontent.com/assets/8760909/20930983/6f5851c6-bbc7-11e6-8c84-c7583e1aa103.PNG)

This was just after the recent update and throws and error on most of my programming syntax's. Was working before without any issues.

**Comment by variadico** [comment]
Did you install an ASP plugin?
What version of Windows are you running?
What channel and build number of Sublime Text are you running?

**Comment by y0ssar1an** [comment]
Thank you for reporting this issue!
Does restarting Sublime fix the problem?
If not, can you post all the output from your console?
![image](https://cloud.githubusercontent.com/assets/1250684/20997463/9f32a736-bcba-11e6-817b-d8fe27e43fe3.png)

**Comment by y0ssar1an** [comment]
@damonx23 Are you still experiencing the issue?

**Comment by lucaspanik** [comment]
I same error in console:
error: Error loading syntax file "Packages/ASP/HTML-ASP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
generating meta info summary

**Comment by lucaspanik** [comment]
**Solution:**
There is a conflict with the CSS plugin (default), disable CSS and be happy!

![53b9e3cf6c1bb32a6eb2c75089a579c84082f82a](https://cloud.githubusercontent.com/assets/7035554/21264563/17ee9cb4-c384-11e6-8ce7-5fa08c8cdb81.gif)

**Comment by y0ssar1an** [comment]
Thank you, @lucaspanik and @damonx23. I've changed the language in the README and install notes. Disabling the default CSS package is no longer "recommended." It's required.
