### ISSUE TITLE
Highlighting in HTML not works

### ISSUE THREAD

**Issue by lucaspanik** [y0ssar1an/CSS3#72]
Highlighting in HTML not works:

Plugin CSS (Enable) and CSS3 (Disable):
![css](https://cloud.githubusercontent.com/assets/7035554/21426792/079dae3c-c838-11e6-8bfe-fa7f48ef70e0.png)

Plugin CSS3 (Enable) and CSS (Disable):
![css3](https://cloud.githubusercontent.com/assets/7035554/21426804/107cfd32-c838-11e6-8adb-25dc319ea397.png)

**Comment by y0ssar1an** [comment]
Thank you for reporting this serious bug! I'm investigating now.

**Comment by lhpopov** [comment]
I can confirm the same issue happening in a .tpl file if it matters.
I just installed the plug-in and followed the steps to enable it.
My system is Windows 10 with Sublime text 3 installed.
![css3](https://cloud.githubusercontent.com/assets/594836/21675535/cc0370d8-d33a-11e6-9141-fe6f8a9ec6c2.jpg)

**Comment by y0ssar1an** [comment]
Unfortunately, I don't have a solution for this. The default HTML package [specifically references a rule in the default CSS package](https://github.com/sublimehq/Packages/blob/master/HTML/HTML.sublime-syntax#L344) to highlight inline CSS. I can think of only two solutions:
1. Petition to have CSS3 replace the default CSS package, then change the default HTML package to reference a CSS3 highlighting rule instead.
  * pros: Everyone using Sublime would get great CSS support out of the box
  * cons: It would take some political effort to get it accepted, and I'm not sure I have the time for this :(
2. Make my own HTML6 package to complement CSS3.
  * pros: It would solve the inline highlighting problem.
  * cons: It would be months of work. Users would have to be guided through installing both packages.

**Comment by Keesromkes** [comment]
Either the problem has resolved itself, or I have a different configuration (mac, sublime3, emmet, kobalt2 theme)

![image](https://cloud.githubusercontent.com/assets/6368490/24395714/d3222ac0-13a0-11e7-939d-7dda355a4975.png)

**Comment by y0ssar1an** [comment]
@Keesromkes That's wonderful if true. Can I ask if you have the default CSS package disabled. The highlighting may be coming from there, or from another package.

**Comment by Keesromkes** [comment]
It might be just that @y0ssar1an, with Kobalt2 active (which also does highlighting it seems) - inline predective code for css3 doesn't work for instance. Sorry for the false flag! (or my lack of knowledge)

**Comment by y0ssar1an** [comment]
No worries. It's good to know about the Kobalt2 package.

**Comment by duggum** [comment]
Not to resurrect a dead issue, but the latest Sublime dev build (3153) is supposed to have fixed the hard reference to the default CSS syntax file by change the default HTML syntax to reference 'rule-list-body' by scope rather than syntax.

**From WBond in the Sublime Dev Build 3153 forum:**

> The issue is that you have disabled the CSS package, per the instructions of the CSS3 author. Unfortunately, disabling the CSS package breaks the HTML syntax. The style attributes need to reference a specific context of the CSS syntax. When you disable the CSS package, it makes that context unavailable. With this build we moved the CSS and JavaScript code in the HTML syntax use the new embed syntax. When it tries to resolve the embedded context, it isn't able to find it.
> 
> Honestly, if the CSS3 package is going to tells users to disable the CSS syntax, it will likely need to include it's own HTML syntax that embeds CSS3 instead of CSS. Alternatively, if the CSS3 syntax can create a context named rule-list-body and I will make sure that the HTML syntax references scope:source.css#rule-list-body for the next build.
> 
> Edit: the HTML syntax now references CSS via scope name, so all the CSS3 author needs to do is create a context named rule-list-body that will properly highlight the contexts of a style="" attribute.

I did a quick copy/paste of the 'rule-list-body' code from the default package into the CSS3 syntax file, plus a couple variables, and it solved the problem.

**Comment by y0ssar1an** [comment]
This should be fixed now in #86. `v2.1.11` should be out shortly. Thanks very much for reporting this!
