### ISSUE TITLE
Support for experimental @document at-rule?

### ISSUE THREAD

**Issue by franklinyu** [y0ssar1an/CSS3#73]
Any plan to support [`@document`](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)? Currently this

```css
@-moz-document domain('github.com') {}
```

complains.

**Comment by y0ssar1an** [comment]
`@document` is technically [not in the spec](https://www.w3.org/TR/2012/WD-css3-conditional-20121213/#changes). It was a part of CSS Conditional Rules Module Level 3 spec, but it was taken out. It's supposed to return in the Level 4 spec, but that doesn't exist yet.

I could be convinced to add it to CSS3, but I think it might be a little premature. The syntax could change completely from the `-moz-` implementation.

**Comment by franklinyu** [comment]
Yes I knew it's not, by calling it "experimental". I am actually not sure what "not being in spec" mean; I guess that even if it goes to spec finally, it would be CSS4?

**Comment by y0ssar1an** [comment]
The CSS "spec" is actually a collection of 40+ specs. Each spec has a different "level", usually between 1 and 4. There's no correlation between the levels of each spec and the CSS version number. Some of the newest stuff is in Level 1 specs. It can be pretty confusing. CSS doesn't really follow any kind of versioning scheme.

Right now, the highest version of the Conditional Rules Module is Level 3. At some unknown time in the future they'll make a Conditional Rules Module Level 4 spec, which may or may not contain `@document`. I follow the spec changes pretty closely, so as soon the Level 4 spec lands, expect to see `@document` in this plugin fairly soon after.

Thanks for bringing this up! I hadn't looked at `@document` in a while and it was worth investigating!

**Comment by franklinyu** [comment]
Thanks a lot for all those introduction to CSS levels! Didn't know anything about that before.

I have just read that

> Initially in [CSS Conditional Rules Module Level 3](https://drafts.csswg.org/css-conditional-3/), `@document` has been postponed to the level 4.

What does that mean? Would there be something like [CSS Conditional Rules Module Level 4](https://drafts.csswg.org/css-conditional-4/) in future?

**Comment by y0ssar1an** [comment]
Yep. Exactly. There's no telling when it will happen, but if I see it mentioned in the specs I'll comment on this issue again and let you know.
