### ISSUE TITLE
"Empty range in char class" error

### ISSUE THREAD

**Issue by clepore** [y0ssar1an/CSS3#74]
This is happening when I reinstall the plugin, or when I have it installed and am opening and closing files. Any thoughts? I made sure I followed all of your settings/preference recommendations.

<img width="690" alt="screen shot 2017-04-04 at 4 13 36 pm" src="https://cloud.githubusercontent.com/assets/742319/24676746/3a1249f2-1952-11e7-85af-fabc87cf8d8c.png">

**Comment by variadico** [comment]
I wonder if you can see anymore information in the console. Maybe try ⌘+` to see if anything interesting is in there.

**Comment by clepore** [comment]
This is what I'm seeing in my console:

I believe the following is because I disabled the `CSS` package and markdown didn't like it:
```
no such context CSS.sublime-syntax#rule-list-body at line 344 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
no such context CSS.sublime-syntax#rule-list-body at line 363 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
no such context CSS.sublime-syntax#rule-list-body at line 344 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
no such context CSS.sublime-syntax#rule-list-body at line 363 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
no such context CSS.sublime-syntax#rule-list-body at line 344 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
no such context CSS.sublime-syntax#rule-list-body at line 363 column 28 in Packages/MarkdownEditing/Markdown.tmLanguage
```

This is where I'm not sure if it helps or not, right up to the error and where ST3 crashes.
```
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used
error: empty range in char class in regex (?=[\w.:#\[*-&]|@nest)
```
