### ISSUE TITLE
Curly braces auto closing

### ISSUE THREAD

**Issue by aristidesfl** [y0ssar1an/CSS3#75]
Is it possible to automatically close curly braces and position the cursor after pressing return?

**Comment by y0ssar1an** [comment]
I'm not sure I understand. When I type `body {`, Sublime creates a closing brace and positions the cursor between the braces. Is that what you mean?

**Comment by aristidesfl** [comment]
I had `"auto_match_enabled": false` in my preferences. No idea why. Thanks!
