### ISSUE TITLE
Breaks multiselect autocomplete in ALL syntaxes

### ISSUE THREAD

**Issue by Mitranim** [y0ssar1an/CSS3#80]

**Comment by y0ssar1an** [comment]
That sounds like a serious bug! 😬 Can you explain what multiselect autocomplete is? Does it mean _offering completions for multiple cursors_?

The problem might be [this code right here](https://github.com/y0ssar1an/CSS3/blob/master/css3_completions.py#L36,L43):
```py
# If there's multiple cursors, we can't offer completions.
#     body {
#         foo: |<- cursor
#         bar: |<- second cursor
#     }
# Which values do we offer? foo's or bar's?
if len(locations) > 1:
    return [], sublime.INHIBIT_WORD_COMPLETIONS
```

**Comment by Mitranim** [comment]
Not sure what makes you think "can't offer completions", because typing inserts the same text on every cursor, and completion, if available, certainly helps. It's a built-in Sublime feature and you shouldn't disable it, _especially_ not in CSS files.

**Comment by y0ssar1an** [comment]
Thanks for reporting this @Mitranim. My attempt at a fix should land on Package Control shortly. Can you please test [v2.1.6](https://github.com/y0ssar1an/CSS3/releases/tag/v2.1.6) and let me know if it solves the problem for you?

**Comment by Mitranim** [comment]
Doesn't inhibit completions in non-CSS files. 👍 Thanks!

Would be even nicer if it allowed normal Sublime completions inside CSS comments. It's trying to: https://github.com/y0ssar1an/CSS3/blob/8ee81862c007861fb8e1af6c24e6034526c006c6/css3_completions.py#L38-L39, but doesn't seem to work for me.
