### ISSUE TITLE
LESS & SASS support

### ISSUE THREAD

**Issue by yacine** [y0ssar1an/CSS3#81]
LESS & SASS support

**Comment by y0ssar1an** [comment]
Yeah, I know there's a big demand for this. The proper way to implement this would be a fork of CSS3 -- a completely separate package on [Package Control](https://packagecontrol.io). There are enough differences between SCSS and CSS that it deserves its own package. I wish I had the time to do this 😬. If there's a company out there that wants to pay me to work on Sublime plugins full-time, please let me know! 😄
