### ISSUE TITLE
CSS3_Syntax please continue...

### ISSUE THREAD

**Issue by anyotherway** [y0ssar1an/CSS3#83]
https://packagecontrol.io/packages/CSS3_Syntax
Using ST2 css-files WITH ST3 html-files, and using ST2 and ST3 together in countless other ways to organize work flow.
Need CSS3 package in ST2 and CSS3_Syntax works fine.
Unblock download!
https://packagecontrol.io/packages/CSS3_Syntax

> "Announcement: For ST3 users, this package has been replaced by CSS3 [only for ST3]. This package will be removed some time after Sublime Text 3 is released." 
-- please NO!
ST3 cannot use CSS3_Syntax and CSS3 does not work with ST2.

Suggestion, instead of smashing down ST2 CSS coders, complete CSS3 so it works with inline CSS and not just CSS files. Also, clean up the perpetual CSS3 package hints mess. And leave ST2 kids alone!

THERE IS ONLY ONE THING WORSE THAN A WORK-HORSE THEIF, A WORK-HORSE KILLER!

**Comment by y0ssar1an** [comment]
Sorry, CSS3_Syntax has been taken down for good. It was woefully out of date and thoroughly broken. I encourage everyone to upgrade to ST3.

**Comment by anyotherway** [comment]
Sweet! Just saying, you guys are making life hard for us Apple multi-taskers.
Good luck on up-coming ST4 :-)
