### ISSUE TITLE
Porting to VSCode / Atom

### ISSUE THREAD

**Issue by octref** [y0ssar1an/CSS3#84]
Hey, I'm working on a VSCode Vue plugin and since many Vue users use PostCSS, I've included a PostCSS grammar to support it. Grammar is taken from here: https://github.com/azat-io/atom-language-postcss

However, that definition is far more incomplete compared to yours. (Great work!)

I'm wondering if it's possible to modify CSS3 grammar to drop Sublime specific syntax and make it available to VSCode / Atom users. I've written some TM grammar so I can help. But I'd like to know if it's just a lot of work or it's downright impossible to modify and a rewrite is necessary.

Thanks!

**Comment by y0ssar1an** [comment]
Once upon a time, CSS3 used TM grammars. I rewrote everything from scratch in the new `sublime-syntax` format for [`v2.0.0`](https://github.com/y0ssar1an/CSS3/releases/tag/v2.0.0). It was a huge step forward for performance, correctness, and maintainability. Still, there was a lot of work that went into the 1.x versions. The most recent is [v1.3.3](https://github.com/y0ssar1an/CSS3/releases/tag/v1.3.3). That version doesn't contain any of the PostCSS work, and it's fallen behind the latest specs by quite a bit. Given what I know now, I'm not sure I'd want to use that as a starting point, but it could be useful as a reference. Just beware that there are a lot more highlighting mistakes in 1.x.

For CSS3, I definitely don't want to go back to the bad ol' days before `sublime-syntax` (sorry!). Although I understand why the VSCode team chose TM grammars, I'm kinda disappointed they didn't come up with a better system. Sublime has gotten rid of most of its XML config files and is slowly cutting the cord to TextMate.

**Comment by octref** [comment]
Yeah, I kinda already expected it to be impossible.
Maintaining a good grammar according to a living spec takes so much effort.

I also understand why Sublime would keep the sublime syntax engine proprietary, although I hope it doesn't, so your work can benefit a much wider audience.

Thanks for your response and have a nice day!
