### ISSUE TITLE
Please update to support Sublime Text 3153 and above 

### ISSUE THREAD

**Issue by Jax0rz** [y0ssar1an/CSS3#85]
After the update I find an error like this with HTML syntax.
![177eca9ffd7f4cc9e784af0def4af7b7e11b8ab5](https://user-images.githubusercontent.com/7557357/32406563-c3ecc0a6-c1b5-11e7-9758-1d503a85e748.png)

The Sublime Text author's explain：

> The issue is that you have disabled the CSS package, per the instructions of the CSS3 author. Unfortunately, disabling the CSS package breaks the HTML syntax. The style attributes need to reference a specific context of the CSS syntax. When you disable the CSS package, it makes that context unavailable. With this build we moved the CSS and JavaScript code in the HTML syntax use the new embed syntax. When it tries to resolve the embedded context, it isn't able to find it.
> 
> Honestly, if the CSS3 package is going to tells users to disable the CSS syntax, it will likely need to include it's own HTML syntax that embeds CSS3 instead of CSS. Alternatively, if the CSS3 syntax can create a context named rule-list-body and I will make sure that the HTML syntax references scope:source.css#rule-list-body for the next build.
> Edit: the HTML syntax now references CSS via scope name, so all the CSS3 author needs to do is create a context named rule-list-body that will properly highlight the contexts of a style="" attribute.

Find More here:

> https://forum.sublimetext.com/t/dev-build-3153/33014/59

**Comment by Nemesis19** [comment]
I can report the same issue

**Comment by y0ssar1an** [comment]
Sorry for the trouble! This should be fixed in #86. The new version should go out on Package Control in under an hour. Please re-open if this does not fix the issue for you.

**Comment by venz111** [comment]
i'm with the latest ST3 and css3 but still getting that error in the console. however css syntax seems to work fine in html and php files.

**Comment by y0ssar1an** [comment]
@venz111 Are you using the latest CSS3?
```
Ctrl + Shift + P > Package Control: Upgrade Package > CSS3
```

**Comment by venz111** [comment]
yes, using the latest.

**Comment by y0ssar1an** [comment]
Can you please post the error logs from your console and your build of ST3 (e.g. 3153)?

**Comment by venz111** [comment]
oh I was fooling myself and I didn't realize 3153 is a dev build. I run latest stable (3143). Sorry about.

**Comment by y0ssar1an** [comment]
No worries! 😀  I'm interested in bugs in dev builds too. The latest dev build is currently 3156. Let me know if you encounter problems with the latest stable or dev builds. Thanks!
