### ISSUE TITLE
Missing pseudo class :fullscreen

### ISSUE THREAD

**Issue by luka-lazov** [y0ssar1an/CSS3#88]
First, your package is great, but it is missing the pseudo class :fullscreen. 
I already added it locally for me, should I make a pull request?

https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

**Comment by y0ssar1an** [comment]
This should be out in the [2.1.14 update]. Package Control takes up to an hour to discover it.

Thanks very much for reporting this, @luka-lazov!
