### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by Jax0rz** [y0ssar1an/CSS3#92]
some css properties doesn't highlighting correctly:
![capto_capture 2018-02-08_19-47-40_](https://user-images.githubusercontent.com/7557357/35971457-f79167f6-0d08-11e8-9294-48b9c53125c0.png)

my ST version is `3156`

**Comment by variadico** [comment]
* `-webkit-box-align` seems non-standard - https://developer.mozilla.org/en-US/docs/Web/CSS/box-align
* `-ms-flex-align` seems non-standard (IE only) - https://msdn.microsoft.com/en-us/library/dn265027(v=vs.85).aspx
* `-webkit-box-pack` seems non-standard - https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack

Looks like it's working as intended. From the readme:
> Bad, old CSS is flagged. Unnecessarily prefixed properties aren't highlighted. ... Follows the W3C specs extremely closely.

Not sure about `grid-gap` though. https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gap

**Comment by y0ssar1an** [comment]
Thank you for the research, @variadico.

I'll add that the `grid-grap` property has been replaced by `gap` in [the CSS Grid Layout Module Level 1 spec](https://drafts.csswg.org/css-grid/#change-2016-grid-gap).

All that code can be deleted unless you have a requirement of supporting very old browsers.

The plugin is working as intended, alerting you to deprecated and nonstandard code. Please reopen this if you feel like some of these old properties should be supported. Thanks!
